# gateway-service/src/main/resources/application.yml
spring:
    cloud:
        gateway:
            routes:
                - id: reservation-service
                  uri: http://localhost:8081
                  predicates:
                      - Path=/reservations/**
                - id: user-service
                  uri: http://localhost:8082
                  predicates:
                      - Path=/users/**
                - id: payment-service
                  uri: http://localhost:8083
                  predicates:
                      - Path=/payments/**
