# payment-service/src/main/resources/application.yml
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/payment_db
        username: root
        password: password
    jpa:
        hibernate:
            ddl-auto: update
    server:
        port: 8083
