spring:
    datasource:
        url: jdbc:mysql://localhost:3306/reservation_db
        username: root
        password: password
    jpa:
        hibernate:
            ddl-auto: update
    server:
        port: 8081
